### ISSUE TITLE
Set Up hybris B2C accelerator using HSQL db

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor_hritsyk#1]
As a **Developer**
I want to have local hybris environment with B2C accelerator (on HSQL db), 
So that I could work with hybris platform on my local machine

**AC:**
1) hybris installed
2) hybris built
3) hybris initialized
4) checkout process could be successfully done

*Tips:*
How to install -- https://wiki.hybris.com/display/tr52/Telco+Accelerator
Development environment setup example -- https://kb.epam.com/display/ECOMCC/Dev-Environment+Setup+for+iPromoTarget+project
EPAM how-to -- https://kb.epam.com/display/ECOMCC/Platform+Installation+Instructions

**In case of checkout trouble, use the following link**
https://wiki.hybris.com/display/accdoc50to56/b2ccheckout+AddOn

**Comment by hritsyk** [comment]
<img width="1027" alt="01" src="https://cloud.githubusercontent.com/assets/15844955/18435784/da77f5e0-78fd-11e6-8d2d-ba27e884dcc7.png">
<img width="1143" alt="02" src="https://cloud.githubusercontent.com/assets/15844955/18435786/da78a832-78fd-11e6-8b62-b2102de5bf38.png">
<img width="997" alt="03" src="https://cloud.githubusercontent.com/assets/15844955/18435783/da77f87e-78fd-11e6-99a7-aa69c20a2253.png">
<img width="1440" alt="04" src="https://cloud.githubusercontent.com/assets/15844955/18435787/da7e80f4-78fd-11e6-85ab-a11414b43a2d.png">
<img width="1440" alt="05" src="https://cloud.githubusercontent.com/assets/15844955/18435785/da77e154-78fd-11e6-9b07-2d68be8202a2.png">
