### ISSUE TITLE
NG cockpit is used to manage customers & organizations entities

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor_hritsyk#11]
As a **content manager**
I want to be able to change customers and organizations attributes in more modern way
So that backoffice extension is added to B2C accelerator

**AC:**
1. Organizations node is added to backoffice objects tree
2. Organizations manager is able to perform CRUD-operations with organizations & customers via backoffice web-page.

*Tips:*
https://wiki.hybris.com/display/release5/Include+-+Create+a+Custom+Backoffice+Extension 
https://wiki.hybris.com/display/tr52/Trail+~+Customizing+Backoffice+-+Cockpit+NG

**Comment by hritsyk** [comment]
<img width="1042" alt="screen shot 2016-09-28 at 17 02 59" src="https://cloud.githubusercontent.com/assets/15844955/18916570/82b4ac98-859d-11e6-9605-6c4b46a89d3d.png">

<img width="1440" alt="screen shot 2016-09-28 at 17 03 16" src="https://cloud.githubusercontent.com/assets/15844955/18916590/90d24524-859d-11e6-8689-0812915e3c70.png">
