### ISSUE TITLE
Let organization customers receive e-mails

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor_hritsyk#12]
As an **organization manager**
I want to be on the same page with organization contents
So that I receive daily email with list of users in my organization

**AC**
Email is sent to each organization manager whose address is set as an Organization.email attribute.
The email should contain list of all users in this organization. 

**Mail server configuration**
mail.from=darwinepam@gmail.com
mail.replyto=darwinepam@gmail.com
mail.smtp.server=smtp.gmail.com
mail.smtp.port=587
mail.smtp.user=darwinepam@gmail.com
mail.smtp.password=DarwinDarwin
mail.smtp.starttls.enable=true
mail.use.tls=true

*Technical tips*
https://wiki.hybris.com/display/tr4/Trail+~+Process+Engine
https://wiki.hybris.com/display/accdoc50to56/Business+Processes+and+Eventing

**Comment by hritsyk** [comment]
<img width="1440" alt="screen shot 2016-09-28 at 17 06 05" src="https://cloud.githubusercontent.com/assets/15844955/18916680/e257fa2e-859d-11e6-8104-a4cecf335cb6.png">
<img width="851" alt="screen shot 2016-09-28 at 17 04 55" src="https://cloud.githubusercontent.com/assets/15844955/18916697/f289cc4c-859d-11e6-8690-67ef3005666c.png">
