### ISSUE TITLE
Run "organization e-mails" job using ant (without hybris started)

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor_hritsyk#13]
As hybris **admin user**
I want to have a possibility to start "organization e-mails" cronjob without having hybris started
So that I have a bat script that starts this cronjob using ant.

**AC**
Needed .bat (or .sh) script is placed into a separate "admin" folder.

*Tips*
https://wiki.hybris.com/display/release5/cronjob+-+Technical+Guide#cronjob-TechnicalGuide-RunningCronJobsThroughAnt

**Comment by hritsyk** [comment]
<img width="644" alt="screen shot 2016-09-28 at 17 08 20" src="https://cloud.githubusercontent.com/assets/15844955/18916763/31db3ee4-859e-11e6-9873-e3802496914d.png">
<img width="760" alt="screen shot 2016-09-28 at 17 14 45" src="https://cloud.githubusercontent.com/assets/15844955/18917041/3acb0218-859f-11e6-9115-d868d786464f.png">
