### ISSUE TITLE
Obtain list of organizations via webservices

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor_hritsyk#14]
As a **mobile developer or developer of integration candidate utility**
I want to have a possibility to obtain list of organizations via REST calls
So that webservices extension is configured properly

**AC**
Webservices extension is turned-on for B2C accelerator

*Tips:*
https://wiki.hybris.com/display/release5/Introduction+to+Web+Services
https://wiki.hybris.com/display/release5/Key+Features+and+Implementation+Details

**Comment by hritsyk** [comment]
<img width="936" alt="screen shot 2016-09-28 at 16 59 35" src="https://cloud.githubusercontent.com/assets/15844955/18917087/57a54d94-859f-11e6-9a58-2ccdbc3ab677.png">
<img width="751" alt="screen shot 2016-09-28 at 17 01 26" src="https://cloud.githubusercontent.com/assets/15844955/18917098/5d4ceb4e-859f-11e6-877a-78775713065b.png">
<img width="601" alt="screen shot 2016-09-28 at 17 01 33" src="https://cloud.githubusercontent.com/assets/15844955/18917104/632f9980-859f-11e6-9c56-11ba72db1fc2.png">
