### ISSUE TITLE
Generate an error message when organization name length is greater than 15 simbols

### ISSUE THREAD

**Issue by HarchenkoMykyta** [HarchenkoMykyta/hybris_mentoring_igor_hritsyk#15]
As a **content manager**
I want to have a constraint for organization's name attribute
So that an appropriate constraint is created via ImpEx and is available in Admin cockpit.

**AC**
Aftert an attempt to set a long value for organization name an appropriate contraint generated an error
Constraint is created using ImpEx and could be changed in Admin cockpit

*Tips:*
https://wiki.hybris.com/display/R5T/Trail+~+Validation

**Comment by hritsyk** [comment]
<img width="1440" alt="screen shot 2016-09-28 at 16 55 38" src="https://cloud.githubusercontent.com/assets/15844955/18917129/7f2434e8-859f-11e6-9246-664e536bd56d.png">
<img width="1417" alt="screen shot 2016-09-28 at 16 57 39" src="https://cloud.githubusercontent.com/assets/15844955/18917153/8cab7932-859f-11e6-91f3-fa45295b4ac2.png">
